#################################################
# DO Community Playbooks: Initial Server Setup
#################################################
---
- hosts: all
  become: true
  gather_facts: no
  ignore_errors: yes
  vars_files:
    - vars/default.yml
  tasks:
    - name: run an executable enable
      become: true
      command: /bin/bash ../apt-install.sh

